name: Release

on:
  push:
    tags:
      - 'v*'
  release:
    types:
      - 'published'
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            libs
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: deps-${{ hashFiles('dependencies.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: |
            deps-

      - name: Run unit tests and build JAR
        run: ./gradlew buildPlugin precompileZip

      - name: upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            build/distributions/*
            build/libs/*
